from pathlib import Path
import re
from datetime import date
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent
IMG = OUT / 'imagenes'

def clean(s): return re.sub(r'\s+', ' ', s).strip()

def sql_tables(folder):
    result=[]
    for f in sorted(folder.glob('*.sql')):
        text=f.read_text(encoding='utf-8', errors='ignore')
        for m in re.finditer(r'CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:(\w+)\.)?(\w+)\s*\((.*?)\);', text, re.I|re.S):
            name=m.group(2); body=m.group(3); cols=[]
            for line in body.splitlines():
                x=clean(line.rstrip(','))
                if not x or x.startswith('--') or re.match(r'(CONSTRAINT|PRIMARY KEY|FOREIGN KEY|UNIQUE|CHECK|EXCLUDE)',x,re.I): continue
                mm=re.match(r'"?([a-zA-Z_][\w]*)"?\s+([\w]+(?:\s*\([^)]*\))?(?:\s+\w+)?)',x)
                if mm:
                    c,t=mm.groups(); flags=[]
                    if re.search(r'PRIMARY\s+KEY',x,re.I): flags.append('PK')
                    if re.search(r'NOT\s+NULL',x,re.I): flags.append('NN')
                    if re.search(r'REFERENCES\s+',x,re.I): flags.append('FK')
                    cols.append((c,t,'; '.join(flags) or '—'))
            if cols and name not in {x[0] for x in result}: result.append((name,cols,f.name))
    return result

pos_tables=sql_tables(ROOT/'database/pos/migrations')
mon_tables=sql_tables(ROOT/'database/monitoreo')

def md_table(headers, rows):
    out=['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']
    for row in rows: out.append('| '+' | '.join(str(v).replace('|','/') for v in row)+' |')
    return '\n'.join(out)+'\n'

def write_md():
    m=[]; add=m.append
    add('# Sistema de Gestión para Heladería Cafetería con Módulo Integrado de Monitoreo de Consumo de Agua y Energía\n')
    add('**Universidad:** [PENDIENTE: universidad]  \n**Facultad:** [PENDIENTE: facultad]  \n**Carrera:** [PENDIENTE: carrera]  \n**Asignatura:** Programación Web II  \n**Integrantes:** [PENDIENTE: integrantes]  \n**Docente:** [PENDIENTE: docente]  \n**Gestión y fecha:** [PENDIENTE: gestión y fecha]\n')
    add('## Hoja de control documental\n'+md_table(['Versión','Fecha','Descripción del cambio','Responsable'],[['1.0',date.today().isoformat(),'Elaboración inicial basada en el repositorio','[PENDIENTE]']]))
    add('## Índice general\n1. Introducción\n2. Ingeniería de requisitos\n3. Modelado UML\n4. Base de datos\n5. Arquitectura del sistema\n6. Desarrollo del sistema\n7. Implementación con Docker\n8. Investigación\n9. Pruebas\n10. Manual de instalación\n11. Manual de despliegue\n12. Conclusiones y recomendaciones\nReferencias y anexos\n')
    add('## Índice de figuras\n1. Casos de uso del POS\n2. Casos de uso del módulo de monitoreo\n3. Modelo entidad relación del POS\n4. Modelo entidad relación del monitoreo\n')
    add('## CAPÍTULO I. INTRODUCCIÓN\n')
    add('### Antecedentes\nLa operación de una heladería/cafetería combina ventas, caja, pedidos, inventario y atención al cliente. Cuando estos procesos se registran por separado, se dificulta mantener la trazabilidad de stock, pagos y turnos. En paralelo, la medición del uso de agua y energía permite identificar consumos que requieren atención. El proyecto integra ambos dominios sin mezclar sus datos: el POS reporta consumos mediante una API y el módulo de monitoreo los procesa y alerta.\n')
    add('### Planteamiento del problema\nSe requiere centralizar la operación diaria del local y disponer de un mecanismo confiable para registrar, clasificar y notificar consumos de recursos. El reto técnico consiste en preservar la autonomía de las dos aplicaciones y, al mismo tiempo, tolerar fallas temporales de comunicación mediante colas, reintentos e idempotencia.\n')
    add('### Justificación\nTécnicamente, la solución aplica una arquitectura por capas, autenticación JWT, RBAC, RLS y transacciones. Socialmente, contribuye a visualizar el uso responsable de agua y energía. Académicamente, integra desarrollo web, bases de datos, seguridad, APIs REST y contenedores.\n')
    add('### Objetivos\n**Objetivo general.** Desarrollar un sistema de gestión para una heladería/cafetería integrado, mediante API REST, con un módulo de monitoreo de agua y energía.\n\n**Objetivos específicos.** Registrar ventas, turnos, pedidos e inventario; preservar la trazabilidad de las operaciones; reportar consumos desde el POS; clasificar consumos y generar alertas; aplicar controles de autenticación, autorización e infraestructura reproducible.\n')
    add('### Alcance, limitaciones, eje transversal y ODS\nEl alcance abarca las aplicaciones POS y Monitoreo, sus frontends React, backends Express, PostgreSQL/Supabase, contratos y despliegue local con Docker. No existe evidencia de una URL pública ni de capturas de ejecución; por ello se consignan como pendientes. El eje transversal es el uso responsable de recursos. El proyecto se alinea con el ODS 6 al registrar consumo de agua, con el ODS 7 al monitorear energía y con el ODS 12 al apoyar decisiones operativas basadas en consumo.\n')
    add('## CAPÍTULO II. INGENIERÍA DE REQUERIMIENTOS\n')
    rf=[('RF01','Registrar venta normal, multiproducto y pagos divididos','Ventas'),('RF02','Rechazar ventas sin stock y restaurar stock en anulaciones/devoluciones','Ventas e inventario'),('RF03','Abrir un único turno por cajero y calcular cierre/diferencia','Caja'),('RF04','Gestionar mesas, pedidos y estados de pedido','Pedidos'),('RF05','Gestionar insumos, proveedores y movimientos de inventario','Inventario'),('RF06','Gestionar productos, categorías y recetas','Catálogo'),('RF07','Gestionar clientes, puntos, promociones y sus validaciones','Clientes y promociones'),('RF08','Autenticar con JWT y autorizar con RBAC','Seguridad'),('RF09','Enviar consumos con reintento y recibir alertas idempotentes','Integración'),('RF10','Registrar, clasificar y alertar consumos por organización','Monitoreo'),('RF11','Gestionar metas, tarifas y recomendaciones','Monitoreo')]
    add('### Requerimientos funcionales\n'+md_table(['Código','Descripción','Módulo'],rf))
    rnf=[('RNF01','Seguridad','JWT, RBAC, RLS, validación y encabezados de seguridad.'),('RNF02','Integridad','Transacciones y funciones PostgreSQL para operaciones críticas.'),('RNF03','Disponibilidad','Colas, reintentos, backoff y health checks.'),('RNF04','Trazabilidad','Auditoría y movimientos de inventario/puntos.'),('RNF05','Portabilidad','Contenedores Docker y manifiestos Kubernetes.'),('RNF06','Mantenibilidad','Separación routes, controllers, services, repositories y models.'),('RNF07','Usabilidad','Interfaces React separadas por dominio.'),('RNF08','Interoperabilidad','Contratos versionados consumption.v1 y alerts.v1.')]
    add('### Requerimientos no funcionales\n'+md_table(['Código','Categoría','Criterio verificable en el repositorio'],rnf))
    add('### Reglas de negocio y restricciones\nUn cajero mantiene un solo turno abierto; una venta anulada conserva historial; no se devuelve más de lo vendido; las operaciones relevantes restauran stock e insumos; los puntos dejan movimiento trazable; los consumos y alertas se deduplican mediante identificadores externos o claves de idempotencia; los umbrales no deben solaparse; las metas aceptan porcentajes de 0 a 100; y las tarifas validan períodos. POS y Monitoreo son propietarios de sus propios datos y no poseen claves foráneas cruzadas.\n')
    add('## CAPÍTULO III. MODELADO UML\n### Casos de uso\nComo se observa en la Figura 1, el POS contempla a cajero, mesero, encargado de inventario, administrador, supervisor y sistema de monitoreo. Sus casos cubren ventas, turnos, pedidos, catálogo, inventario, clientes, promociones, devoluciones e integración. La Figura 2 presenta responsables de recursos, administrador, supervisor, POS y sistema externo; incluye recepción, registro, clasificación, alertas, metas, tarifas, notificaciones, recomendaciones y reportes.\n\n![Figura 1. Diagrama de casos de uso del POS. Fuente: repositorio del proyecto.](imagenes/pos-casos-de-uso.png)\n\n![Figura 2. Diagrama de casos de uso del módulo de monitoreo. Fuente: repositorio del proyecto.](imagenes/monitoreo-casos-de-uso.png)\n')
    cases=[('Registrar venta','Cajero','JWT válido, permiso y turno abierto','Valida productos, stock, total y pagos; registra venta y descuenta existencias.','Stock o pagos inválidos: rechaza la operación.','Venta activa, movimientos y auditoría.'),('Cerrar turno','Cajero','Turno abierto propio','Calcula ventas, efectivo esperado, diferencia y consumo.','Monto final inválido: rechaza.','Turno cerrado y eventos de integración.'),('Anular venta','Supervisor','Venta activa y permiso','Verifica estado, restaura existencias y audita.','Venta inexistente o anulada: rechaza.','Venta anulada con historial.'),('Procesar devolución','Usuario autorizado','Venta y cantidades válidas','Valida límite, registra devolución y restituye stock.','Cantidad superior a la vendida: rechaza.','Devolución y trazabilidad.'),('Recibir consumo reportado','Sistema POS','Credencial de integración válida','Valida contrato y clave idempotente; registra recepción y encola.','Duplicado: informa recepción previa.','Consumo recibido una sola vez.'),('Clasificar consumo','Worker de monitoreo','Registro de consumo pendiente','Compara con umbrales de recurso y periodo.','Sin umbral aplicable: queda sin clasificación verificable.','Nivel de clasificación asignado.'),('Generar alerta','Worker de monitoreo','Exceso clasificado','Crea alerta y entrega para POS.','Sin destinatario/configuración: queda pendiente.','Alerta registrada y encolada.')]
    add('### Descripción de casos de uso\n'+md_table(['Caso','Actor','Precondición','Flujo principal','Alternativo/excepción','Postcondición'],cases))
    add('### Diagrama de clases\nLas clases principales del POS son Usuario, Rol, Permiso, TurnoCaja, Venta, DetalleVenta, Pago, Producto, Insumo, RecetaInsumo, MovimientoInventario, Cliente, MovimientoPuntos, Pedido, Mesa, Promocion, ConsumoReportado y ColaIntegracion. En Monitoreo se organizan Organizacion, UsuarioOrganizacion, PuntoMedicion, TipoRecurso, RegistroConsumo, UmbralClasificacion, Alerta, Notificacion, MetaReduccion, Tarifa, Recomendacion, RecepcionConsumoPOS y ColaProcesamiento. Las asociaciones internas materializan cardinalidades de propiedad; la integración entre aplicaciones se expresa únicamente por contratos REST.\n')
    add('## CAPÍTULO IV. BASE DE DATOS\n### Modelo relacional\nLa Figura 3 y la Figura 4 muestran dos modelos relacionales independientes. No existe una FK entre ambos esquemas: los identificadores externos se intercambian por las APIs de integración.\n\n![Figura 3. Modelo entidad relación del POS. Fuente: repositorio del proyecto.](imagenes/pos-entidades-relacional.png)\n\n![Figura 4. Modelo entidad relación del monitoreo. Fuente: repositorio del proyecto.](imagenes/monitoreo-entidades-relacional.png)\n')
    add('### Diccionario de datos\nEl siguiente diccionario se genera de las sentencias `CREATE TABLE` disponibles en las migraciones canónicas. Las marcas PK, FK y NN proceden de la misma definición; si una migración no contiene una tabla se evita inferirla.\n')
    for system,tables in [('POS',pos_tables),('Monitoreo',mon_tables)]:
        add(f'#### {system}\n')
        for name, cols, src in tables:
            add(f'**{name}** (fuente: `database/{"pos/migrations" if system=="POS" else "monitoreo"}/{src}`)\n')
            add(md_table(['Columna','Tipo','Restricción'],cols))
    add('La convención del proyecto prioriza UUID para claves y NUMERIC para cantidades o dinero, evitando float en operaciones sensibles.\n')
    add('## CAPÍTULO V. ARQUITECTURA DEL SISTEMA\n### Arquitectura lógica\nEl diseño previsto sigue routes → controllers → services → repositories → models. La documentación de arquitectura advierte que, en el POS, existen handlers inline y los controladores son una abstracción futura; esta es una inconsistencia entre el objetivo por capas y parte de la implementación actual.\n\n### Arquitectura física y de despliegue\nDocker Compose define cuatro servicios: pos-backend (3000), monitoreo-backend (4000), pos-frontend (5173 a 80) y monitoreo-frontend (5174 a 80). Las bases PostgreSQL/Supabase son gestionadas externamente. Kubernetes incluye namespace, deployments, services, ingress, ConfigMap, secretos de ejemplo y HPA. AWS se encuentra previsto, sin una arquitectura IaC verificable.\n\n```text\nPOS frontend -> POS backend -> PostgreSQL/Supabase\n                         | ColaIntegracion -> API Monitoreo -> cola -> RegistroConsumo -> Alerta\nMonitoreo frontend -> Monitoreo backend -> PostgreSQL/Supabase                 -> API POS\n```\n')
    add('## CAPÍTULO VI. DESARROLLO DEL SISTEMA\n### Tecnologías y estructura\n'+md_table(['Capa','Tecnología real','Evidencia'],[['Frontend','React 18 POS y React 19 Monitoreo con Vite','pos/frontend y monitoreo/frontend'],['Backend','Node.js y Express 5','src/app.js de ambos backends'],['ORM','Sequelize 6','src/models'],['Datos','PostgreSQL en Supabase','migraciones y variables de entorno'],['Seguridad','Supabase Auth, JWT, RBAC, RLS, zod, helmet, cors y rate limit','middlewares y shared/docs'],['Infraestructura','Docker, Kubernetes y AWS previsto','docker-compose.yml e infrastructure']]))
    add('El equipo empleó Node.js/Express/React/PostgreSQL como equivalente arquitectónico a la plantilla académica que mencionaba Laravel/PHP/Blade/MySQL. La equivalencia conserva rutas, controladores o handlers, middleware, ORM, migraciones, autenticación y contenedores, sin atribuir al repositorio tecnologías PHP que no contiene. Los modelos Sequelize se ubican en `pos/posBackend/src/models` y `monitoreo/backend/src/models`; las vistas son páginas y componentes React. La estrategia Git indicada establece main, develop y ramas feature, con revisión hacia develop.\n')
    add('## CAPÍTULO VII. IMPLEMENTACIÓN CON DOCKER\nLos Dockerfiles verificados son `pos/posBackend/Dockerfile`, `pos/frontend/Dockerfile`, `monitoreo/backend/Dockerfile` y `monitoreo/frontend/Dockerfile`. `docker-compose.yml` coordina los cuatro servicios, dependencias de frontend con health checks y límites declarados de CPU/memoria. Las variables se documentan en `.env.example` de la raíz y de las aplicaciones. El frontend de monitoreo utiliza `monitoreo/frontend/nginx.conf`; el frontend POS contiene su configuración Nginx en su Dockerfile. Se agregaron `.dockerignore` a los cuatro servicios para excluir node_modules, .env, dist, coverage y .git. Compose construye imágenes, ejecuta contenedores que se resuelven por red interna y, en este caso, no define volúmenes persistentes porque PostgreSQL está gestionado externamente.\n\n[INSERTAR CAPTURA: salida completa de docker compose build. Guardar como docs/proyecto-final/evidencias/07-docker-build.png. Comando: `docker compose build`]\n\n[INSERTAR CAPTURA: servicios iniciados con docker compose up -d. Guardar como docs/proyecto-final/evidencias/07-docker-up.png. Comando: `docker compose up -d`]\n\n[INSERTAR CAPTURA: estado y puertos de los cuatro servicios. Guardar como docs/proyecto-final/evidencias/07-docker-ps.png. Comando: `docker compose ps`]\n\n[INSERTAR CAPTURA: registros de los servicios. Guardar como docs/proyecto-final/evidencias/07-docker-logs.png. Comando: `docker compose logs`]\n\n[INSERTAR CAPTURA: POS y Monitoreo funcionando en Docker. Guardar como docs/proyecto-final/evidencias/07-sistema-docker.png.]\n')
    add('## CAPÍTULO VIII. INVESTIGACIÓN EN FORMATO IMRyD\n### Introducción\nUn hosting publica una aplicación en infraestructura accesible por red. Docker empaqueta procesos y sus dependencias en imágenes reproducibles; por ello facilita trasladar un servicio desde el entorno local a una plataforma compatible.\n\n### Metodología\nSe compararon Render, Railway y Koyeb a partir de su documentación oficial, considerando compatibilidad Docker, integración desde repositorio, HTTPS, servicios y restricciones de plan. La selección definitiva y el despliegue real permanecen pendientes de evidencia del equipo.\n\n### Resultados\n'+md_table(['Plataforma','Docker','Forma de despliegue','Adecuación al proyecto'],[['Render','Construye desde Dockerfile o ejecuta imagen','Repositorio/Dockerfile','Adecuada para publicar cada servicio.'],['Railway','Usa Dockerfile si existe; no ejecuta compose directamente','Un servicio por cada servicio Compose','Adecuada si se mapean los cuatro servicios y variables.'],['Koyeb','Admite contenedores o repositorios Git','Git o imagen Docker','Alternativa para servicios contenerizados.']]))
    add('[INSERTAR CAPTURA: proceso de despliegue en la plataforma elegida. Guardar como docs/proyecto-final/evidencias/08-despliegue.png.]\n\n**URL pública:** [PENDIENTE: URL pública y plataforma elegida].\n\n[INSERTAR CAPTURA: sistema accesible mediante URL pública. Guardar como docs/proyecto-final/evidencias/08-sistema-publico.png.]\n\n### Discusión y conclusiones\nRailway resulta una alternativa coherente para una publicación futura porque su documentación explica cómo traducir un Compose a servicios separados; sin embargo, no se afirma que haya sido elegida ni utilizada. La decisión debe considerar costo vigente, secretos, dominio, observabilidad y límites del plan en el momento del despliegue.\n')
    add('## CAPÍTULO IX. PRUEBAS\nLa prueba integrada existente define 17 pasos, desde abrir turno hasta confirmar alertas, idempotencia, anulación y auditoría. Se identificaron suites de Jest/Vitest en POS y pruebas unitarias e integración en Monitoreo. El resultado real de ejecución no se inventa y queda pendiente de evidencia.\n')
    tests=[('CP01','Venta normal y multiproducto','Turno y stock','Registrar venta','Venta activa y totales correctos','[PENDIENTE]','Pendiente'),('CP02','Pago dividido','Turno abierto','Registrar pagos','Suma igual al total','[PENDIENTE]','Pendiente'),('CP03','Stock insuficiente','Producto sin stock','Intentar venta','Rechazo sin cambios','[PENDIENTE]','Pendiente'),('CP04','Anulación y devolución','Venta activa','Anular/devolver','Stock e insumos restituidos','[PENDIENTE]','Pendiente'),('CP05','Cierre de turno','Turno abierto','Cerrar con monto final','Diferencia y dos consumos','[PENDIENTE]','Pendiente'),('CP06','Idempotencia POS a Monitoreo','Consumo enviado','Reintentar worker','Sin consumo duplicado','[PENDIENTE]','Pendiente'),('CP07','Alerta a POS','Alerta encolada','Reenviar alerta','Una alerta POS','[PENDIENTE]','Pendiente'),('CP08','Seguridad API','Token/payload inválido','Solicitar endpoint','Rechazo controlado','[PENDIENTE]','Pendiente'),('CP09','Resiliencia','Monitoreo no disponible','Procesar cola','Reintento/backoff y recuperación','[PENDIENTE]','Pendiente'),('CP10','Monitoreo','Datos de consumo y umbral','Registrar y clasificar','Nivel, alerta y notificación','[PENDIENTE]','Pendiente')]
    add(md_table(['ID','Caso','Precondición','Pasos','Esperado','Obtenido','Estado'],tests))
    add('[INSERTAR CAPTURA: ejecución de npm test en cada aplicación. Guardar como docs/proyecto-final/evidencias/09-pruebas.png. Comandos: `cd pos/posBackend && npm test`; `cd monitoreo/backend && npm test`; `cd pos/frontend && npm test`; `cd monitoreo/frontend && npm test`.]\n')
    add('## CAPÍTULO X. MANUAL DE INSTALACIÓN\n1. Instalar Docker Desktop con Docker Compose. 2. Copiar `.env.example` a `.env` en la raíz y completar las credenciales de Supabase, las URLs y las API keys; no publicar secretos. 3. Desde la raíz ejecutar `docker compose build` y luego `docker compose up -d`. 4. Consultar `docker compose ps` y `docker compose logs`. 5. Abrir POS en `http://localhost:5173`, Monitoreo en `http://localhost:5174`, POS backend en el puerto 3000 y Monitoreo backend en el puerto 4000. La base de datos es Supabase/PostgreSQL externa, por lo que las migraciones y credenciales deben estar previamente disponibles.\n')
    add('## CAPÍTULO XI. MANUAL DE DESPLIEGUE\n1. Elegir plataforma y crear proyecto. 2. Configurar cuatro servicios a partir de los Dockerfiles, con sus directorios de contexto. 3. Cargar secretos exclusivamente en el gestor de variables de la plataforma. 4. Configurar URLs internas de POS y Monitoreo, CORS y health checks. 5. Publicar los frontends y verificar los endpoints. 6. Ejecutar la prueba integrada y conservar capturas. [PENDIENTE: plataforma, URL y evidencia de despliegue real.]\n')
    add('## CAPÍTULO XII. CONCLUSIONES Y RECOMENDACIONES\nEl repositorio materializa dos aplicaciones separadas que integran operación comercial y monitoreo de recursos mediante APIs y colas. La separación de datos, la idempotencia y la trazabilidad son decisiones centrales. Se recomienda ejecutar y registrar la matriz de pruebas, unificar la documentación del puerto 4000/4001, declarar formalmente la migración canónica del POS, completar una arquitectura AWS o IaC si se adopta esa plataforma, añadir CI/CD y obtener evidencia de despliegue público.\n')
    add('## Inconsistencias detectadas\n- El README de `monitoreo/backend` indica puerto 4001, mientras `.env.example`, Docker Compose y Kubernetes usan 4000; este informe usa 4000.\n- La arquitectura declara capa de controladores, pero la documentación del POS reporta handlers inline en rutas.\n- La documentación de arquitectura menciona 25 suites y 137 tests del backend POS; el prompt maestro habla de aproximadamente 34 suites. Se evita afirmar un conteo único sin una ejecución actual.\n- Existen migraciones del POS en varias ubicaciones; `database/pos/migrations` se usa como fuente canónica en este documento conforme a la documentación del proyecto.\n')
    add('## Referencias bibliográficas\nDocker. (s. f.). *Docker Compose*. https://docs.docker.com/compose/\n\nKoyeb. (s. f.). *Documentation*. https://www.koyeb.com/docs\n\nKubernetes. (s. f.). *Service*. https://kubernetes.io/docs/concepts/services-networking/service/\n\nRailway. (s. f.). *Deploy a Docker Compose app to production*. https://docs.railway.com/guides/docker-compose\n\nRender. (s. f.). *Docker on Render*. https://render.com/docs/docker\n\nProyecto Heladería Monitoreo. (2026). *Código fuente y documentación interna del repositorio*.\n')
    add('## Anexos\n### Pendientes\n- [x] `.dockerignore` creado en los cuatro servicios.\n- [ ] Portada institucional: universidad, facultad, carrera, integrantes, docente y gestión.\n- [ ] URL pública de hosting.\n- [ ] Capturas de Docker, pruebas y despliegue.\n- [ ] Resultados obtenidos de matriz de pruebas.\n- [ ] Video de demostración.\n- [ ] Confirmación de plataforma de hosting.\n- [ ] Arquitectura AWS/IaC, si AWS será utilizado.\n- [ ] CI/CD, recomendado.\n\n### Lista de verificación final\n- [x] Documento en Markdown, Word y PDF.\n- [ ] Repositorio GitHub actualizado por el usuario.\n- [x] Dockerfile y docker-compose incluidos mediante referencia.\n- [ ] Proyecto funcional mediante Docker: requiere capturas/ejecución.\n- [ ] Proyecto publicado en hosting con URL pública.\n- [x] Investigación IMRyD documentada.\n- [ ] Video de demostración.\n- [x] Manual de instalación y despliegue.\n- [x] Estructura APA 7 aplicada de forma base; revisar los datos institucionales antes de entrega.\n')
    (OUT/'DOCUMENTO-FINAL.md').write_text('\n'.join(m),encoding='utf-8')

def shade(cell, fill='1F4E79'):
    tcPr=cell._tc.get_or_add_tcPr(); shd=OxmlElement('w:shd'); shd.set(qn('w:fill'),fill); tcPr.append(shd)
def set_cell(cell,text,bold=False,color=None):
    cell.text=''; p=cell.paragraphs[0]; p.alignment=WD_ALIGN_PARAGRAPH.LEFT; r=p.add_run(str(text)); r.bold=bold; r.font.size=Pt(8); r.font.name='Times New Roman'; r._element.rPr.rFonts.set(qn('w:hAnsi'),'Times New Roman');
    if color: r.font.color.rgb=RGBColor(*color)
    cell.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
def add_table(doc, headers, rows):
    t=doc.add_table(rows=1,cols=len(headers)); t.style='Table Grid'; t.alignment=WD_TABLE_ALIGNMENT.CENTER
    for c,h in zip(t.rows[0].cells,headers): shade(c); set_cell(c,h,True,(255,255,255))
    for ix,row in enumerate(rows):
        cells=t.add_row().cells
        for c,v in zip(cells,row):
            if ix%2: shade(c,'EAF2F8')
            set_cell(c,v)
    doc.add_paragraph()
def add_para(doc,text,style=None):
    p=doc.add_paragraph(style=style); p.paragraph_format.line_spacing=1.5; p.paragraph_format.space_after=Pt(6); p.add_run(text); return p
def add_heading(doc,text,level=1):
    p=doc.add_heading(text,level=level); p.paragraph_format.space_before=Pt(12); p.paragraph_format.space_after=Pt(6); return p
def add_figure(doc,file,num,title):
    p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; p.add_run().add_picture(str(IMG/file),width=Inches(6.1))
    cap=doc.add_paragraph(); cap.alignment=WD_ALIGN_PARAGRAPH.CENTER; cap.add_run(f'Figura {num}. {title}. Fuente: repositorio del proyecto.').italic=True

def write_docx():
    d=Document(); sec=d.sections[0]; sec.top_margin=Inches(1); sec.bottom_margin=Inches(1); sec.left_margin=Inches(1); sec.right_margin=Inches(1)
    normal=d.styles['Normal']; normal.font.name='Times New Roman'; normal._element.rPr.rFonts.set(qn('w:hAnsi'),'Times New Roman'); normal.font.size=Pt(12)
    for name in ['Title','Heading 1','Heading 2','Heading 3']:
        s=d.styles[name]; s.font.name='Times New Roman'; s._element.rPr.rFonts.set(qn('w:hAnsi'),'Times New Roman'); s.font.color.rgb=RGBColor(0,0,0)
    footer=sec.footer.paragraphs[0]; footer.alignment=WD_ALIGN_PARAGRAPH.CENTER; footer.add_run('Sistema Heladería Cafetería y Monitoreo')
    p=d.add_paragraph(style='Title'); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; p.add_run('Sistema de Gestión para Heladería Cafetería con Módulo Integrado de Monitoreo de Consumo de Agua y Energía')
    for x in ['Universidad: [PENDIENTE: universidad]','Facultad: [PENDIENTE: facultad]','Carrera: [PENDIENTE: carrera]','Asignatura: Programación Web II','Integrantes: [PENDIENTE: integrantes]','Docente: [PENDIENTE: docente]','Gestión y fecha: [PENDIENTE: gestión y fecha]']:
        p=d.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; p.add_run(x)
    d.add_page_break(); add_heading(d,'Hoja de control documental'); add_table(d,['Versión','Fecha','Descripción del cambio','Responsable'],[['1.0',date.today().isoformat(),'Elaboración inicial basada en el repositorio','[PENDIENTE]']])
    add_heading(d,'Índice general'); add_para(d,'Capítulo I. Introducción; Capítulo II. Ingeniería de requisitos; Capítulo III. Modelado UML; Capítulo IV. Base de datos; Capítulo V. Arquitectura; Capítulo VI. Desarrollo; Capítulo VII. Docker; Capítulo VIII. Investigación; Capítulo IX. Pruebas; Capítulo X. Instalación; Capítulo XI. Despliegue; Capítulo XII. Conclusiones; referencias y anexos.')
    add_heading(d,'Índice de figuras'); add_table(d,['N.º','Figura'],[['1','Casos de uso del POS'],['2','Casos de uso del módulo de monitoreo'],['3','Modelo entidad relación del POS'],['4','Modelo entidad relación del monitoreo']])
    sections=[('CAPÍTULO I. INTRODUCCIÓN',[('Antecedentes','La operación de una heladería/cafetería integra ventas, caja, pedidos, inventario y atención al cliente. El proyecto centraliza estos procesos y añade una aplicación autónoma para registrar, clasificar y alertar sobre el consumo de agua y energía.'),('Planteamiento del problema','Se requiere preservar la trazabilidad de ventas, pagos, stock y turnos, a la vez que se registran consumos operativos. La integración debe tolerar indisponibilidad temporal sin compartir tablas entre aplicaciones.'),('Justificación','La propuesta aplica arquitectura por capas, API REST, transacciones, JWT, RBAC, RLS y contenedores. Contribuye al uso responsable de recursos y permite aplicar conocimientos de programación web y bases de datos.'),('Objetivos','Objetivo general: desarrollar un sistema de gestión para heladería/cafetería integrado por API con un módulo de monitoreo de agua y energía. Objetivos específicos: registrar operación comercial, trazabilidad e inventario; reportar consumo; clasificar y alertar; y aplicar seguridad e infraestructura reproducible.'),('Alcance y ODS','Incluye POS, Monitoreo, React, Express, Sequelize, PostgreSQL/Supabase, contratos, Docker y manifiestos Kubernetes. Se alinea con ODS 6, ODS 7 y ODS 12. La URL pública y la evidencia de despliegue permanecen pendientes.')]),('CAPÍTULO II. INGENIERÍA DE REQUERIMIENTOS',[]) ]
    for title,subs in sections:
        add_heading(d,title)
        for h,t in subs: add_heading(d,h,2); add_para(d,t)
    add_heading(d,'Requerimientos funcionales',2); add_table(d,['Código','Descripción','Módulo'],[('RF01','Registrar venta normal, multiproducto y pagos divididos','Ventas'),('RF02','Rechazar venta sin stock; anular y devolver con reposición','Ventas/inventario'),('RF03','Abrir/cerrar turno, calcular diferencia y consumo','Caja'),('RF04','Gestionar mesas y pedidos','Pedidos'),('RF05','Gestionar inventario, recetas, clientes y promociones','POS'),('RF06','Enviar consumos y recibir alertas de forma idempotente','Integración'),('RF07','Registrar, clasificar y alertar consumos','Monitoreo'),('RF08','Gestionar metas, tarifas, notificaciones y recomendaciones','Monitoreo')])
    add_heading(d,'Requerimientos no funcionales',2); add_table(d,['Código','Categoría','Criterio'],[('RNF01','Seguridad','JWT, RBAC, RLS, validación y rate limiting.'),('RNF02','Integridad','Transacciones y funciones PostgreSQL para operaciones críticas.'),('RNF03','Disponibilidad','Colas, reintentos, backoff y health checks.'),('RNF04','Trazabilidad','Auditoría y movimientos.'),('RNF05','Portabilidad','Docker y Kubernetes.'),('RNF06','Mantenibilidad','Capas, contratos y módulos separados.')])
    add_heading(d,'Reglas de negocio y restricciones',2); add_para(d,'Un cajero mantiene un único turno abierto. Las ventas anuladas conservan historial. Las devoluciones no pueden superar lo vendido. El stock, los insumos y los puntos dejan trazabilidad. Los consumos y alertas se procesan idempotentemente. Los umbrales no se solapan, las metas se limitan a 0-100 %, y POS/Monitoreo no tienen claves foráneas cruzadas.')
    add_heading(d,'CAPÍTULO III. MODELADO UML'); add_para(d,'La Figura 1 representa los casos de uso del POS y la Figura 2 los del monitoreo. Los actores identificados incluyen cajero, mesero, encargado de inventario, administrador, supervisor, responsable de recursos, sistema POS y sistema de monitoreo.')
    add_figure(d,'pos-casos-de-uso.png',1,'Diagrama de casos de uso del POS'); add_figure(d,'monitoreo-casos-de-uso.png',2,'Diagrama de casos de uso del módulo de monitoreo')
    add_heading(d,'Descripción de casos de uso críticos',2); add_table(d,['Caso','Actor','Precondición','Flujo','Alternativo','Postcondición'],[('Registrar venta','Cajero','JWT, permiso, turno','Valida stock/pagos y registra','Stock o pago inválido','Venta y auditoría'),('Cerrar turno','Cajero','Turno abierto','Calcula efectivo y consumo','Monto inválido','Turno cerrado'),('Anular venta','Supervisor','Venta activa','Restituye existencias','Ya anulada','Historial conservado'),('Procesar devolución','Usuario autorizado','Venta válida','Valida cantidades y restituye','Supera vendido','Devolución trazable'),('Recibir consumo','POS','Credencial integración','Valida y encola','Duplicado','Una recepción'),('Clasificar consumo','Worker','Registro pendiente','Compara umbral','Sin umbral','Nivel asignado'),('Generar alerta','Worker','Exceso','Crea y encola alerta','Sin destinatario','Entrega pendiente')])
    add_heading(d,'Diagrama de clases',2); add_para(d,'En POS, Usuario, Rol y Permiso sustentan el acceso; Venta, DetalleVenta, Pago y TurnoCaja modelan operación; Producto, Insumo, RecetaInsumo y MovimientoInventario modelan existencias. En Monitoreo, Organizacion, PuntoMedicion, TipoRecurso, RegistroConsumo, UmbralClasificacion y Alerta constituyen el núcleo. Las clases de colas y recepción aíslan la integración REST.')
    add_heading(d,'CAPÍTULO IV. BASE DE DATOS'); add_para(d,'Las Figuras 3 y 4 describen bases independientes sin claves foráneas cruzadas. Se priorizan UUID y NUMERIC para claves, dinero y cantidades.')
    add_figure(d,'pos-entidades-relacional.png',3,'Modelo entidad relación del POS'); add_figure(d,'monitoreo-entidades-relacional.png',4,'Modelo entidad relación del monitoreo')
    add_heading(d,'Diccionario de datos',2)
    for system,tables in [('POS',pos_tables),('Monitoreo',mon_tables)]:
        add_heading(d,system,3)
        for name,cols,src in tables:
            add_heading(d,f'{name} - {src}',3); add_table(d,['Columna','Tipo','Restricción'],cols)
    add_heading(d,'CAPÍTULO V. ARQUITECTURA DEL SISTEMA'); add_para(d,'La arquitectura prevista es routes → controllers → services → repositories → models. La documentación registra handlers inline en rutas del POS, por lo que se reporta como diferencia de implementación. Docker Compose coordina cuatro servicios y Supabase provee la base externa. Kubernetes contiene recursos de despliegue; AWS está previsto sin una arquitectura IaC verificable.')
    add_heading(d,'Flujo de integración',2); add_para(d,'POS cierra turno, calcula y guarda ConsumoReportado; ColaIntegracion y un worker envían el contrato consumption.v1 a Monitoreo. Allí se registra la recepción idempotente, se procesa, clasifica y genera alerta. La alerta se entrega al POS mediante alerts.v1, evitando duplicados.')
    add_heading(d,'CAPÍTULO VI. DESARROLLO DEL SISTEMA'); add_table(d,['Capa','Tecnología','Evidencia'],[('Frontend','React 18/19 y Vite','pos/frontend, monitoreo/frontend'),('Backend','Node.js y Express 5','app.js'),('ORM','Sequelize 6','src/models'),('Datos','PostgreSQL/Supabase','migraciones'),('Seguridad','JWT, RBAC, RLS, zod, helmet, cors','middlewares/shared docs'),('Infraestructura','Docker, Kubernetes, AWS previsto','infrastructure')]); add_para(d,'La plantilla académica que menciona Laravel se traduce al stack real Node.js/Express/React/PostgreSQL. No se atribuye PHP, Blade, Eloquent o MySQL al repositorio. Los modelos Sequelize, rutas, middleware y páginas React cumplen los roles equivalentes.')
    add_heading(d,'CAPÍTULO VII. IMPLEMENTACIÓN CON DOCKER'); add_para(d,'Se verificaron cuatro Dockerfiles: POS backend y frontend, Monitoreo backend y frontend. docker-compose.yml expone 3000, 4000, 5173 y 5174; incluye health checks y límites de recursos. Se añadieron .dockerignore en los cuatro contextos para evitar copiar dependencias, secretos y artefactos.')
    for cap in ['[INSERTAR CAPTURA: docker compose build. Ruta: docs/proyecto-final/evidencias/07-docker-build.png.]','[INSERTAR CAPTURA: docker compose up -d. Ruta: docs/proyecto-final/evidencias/07-docker-up.png.]','[INSERTAR CAPTURA: docker compose ps. Ruta: docs/proyecto-final/evidencias/07-docker-ps.png.]','[INSERTAR CAPTURA: docker compose logs. Ruta: docs/proyecto-final/evidencias/07-docker-logs.png.]','[INSERTAR CAPTURA: sistema en Docker. Ruta: docs/proyecto-final/evidencias/07-sistema-docker.png.]']: add_para(d,cap)
    add_heading(d,'CAPÍTULO VIII. INVESTIGACIÓN EN FORMATO IMRyD'); add_heading(d,'Introducción y metodología',2); add_para(d,'El hosting publica aplicaciones en red y Docker las distribuye como imágenes reproducibles. Se compararon Render, Railway y Koyeb a través de sus sitios oficiales por compatibilidad Docker, gestión desde repositorio, HTTPS, servicios, secretos y limitaciones de plan.')
    add_heading(d,'Resultados y discusión',2); add_table(d,['Plataforma','Docker','Conclusión'],[('Render','Construye desde Dockerfile o usa imagen','Apta para servicios individuales.'),('Railway','Usa Dockerfile; traduce cada servicio Compose','Apta si se crean cuatro servicios.'),('Koyeb','Admite contenedores o repositorios Git','Alternativa contenerizada.')]); add_para(d,'[PENDIENTE: plataforma elegida, URL pública y evidencia.] No se afirma un despliegue no verificado.')
    add_heading(d,'CAPÍTULO IX. PRUEBAS'); add_para(d,'Existe un runbook integrado de 17 pasos para turnos, ventas, consumos, idempotencia, alertas, anulación y auditoría. Se identificaron pruebas Jest/Vitest en POS y unitarias/integración en Monitoreo. Los resultados reales requieren ejecución.')
    add_table(d,['ID','Caso','Esperado','Resultado','Estado'],[('CP01','Venta y pago dividido','Venta y total válidos','[PENDIENTE]','Pendiente'),('CP02','Stock insuficiente','Rechazo sin cambios','[PENDIENTE]','Pendiente'),('CP03','Anulación/devolución','Stock restaurado','[PENDIENTE]','Pendiente'),('CP04','Cierre de turno','Diferencia y consumos','[PENDIENTE]','Pendiente'),('CP05','Idempotencia','Sin duplicados','[PENDIENTE]','Pendiente'),('CP06','Seguridad','Rechazo JWT/payload/permiso','[PENDIENTE]','Pendiente'),('CP07','Resiliencia','Reintento y recuperación','[PENDIENTE]','Pendiente')])
    add_para(d,'[INSERTAR CAPTURA: ejecución de pruebas npm test en cada aplicación. Ruta: docs/proyecto-final/evidencias/09-pruebas.png.]')
    add_heading(d,'CAPÍTULO X. MANUAL DE INSTALACIÓN'); add_para(d,'Instalar Docker Desktop. Copiar .env.example a .env y completar secretos sin publicarlos. Desde la raíz ejecutar docker compose build y docker compose up -d. Verificar con docker compose ps y docker compose logs. Abrir http://localhost:5173 (POS), http://localhost:5174 (Monitoreo), y usar puertos 3000/4000 para backends. Supabase debe tener las migraciones y credenciales disponibles.')
    add_heading(d,'CAPÍTULO XI. MANUAL DE DESPLIEGUE'); add_para(d,'Seleccionar una plataforma, crear cuatro servicios a partir de sus Dockerfiles, cargar secretos en su gestor de variables, configurar URLs internas, CORS y health checks, publicar frontends y ejecutar la prueba integrada. [PENDIENTE: plataforma, URL y capturas de despliegue.]')
    add_heading(d,'CAPÍTULO XII. CONCLUSIONES Y RECOMENDACIONES'); add_para(d,'El repositorio implementa dos aplicaciones separadas que integran operación comercial y monitoreo por API y colas. La separación de datos, idempotencia y trazabilidad son decisiones centrales. Se recomienda ejecutar la matriz de pruebas, unificar el puerto 4000/4001, formalizar la migración canónica, completar IaC/AWS si procede, añadir CI/CD y publicar evidencia de un despliegue real.')
    add_heading(d,'Inconsistencias detectadas'); add_table(d,['Hallazgo','Tratamiento en este informe'],[('Puerto de Monitoreo','README indica 4001; env, Compose y K8s indican 4000. Se usa 4000.'),('Capa de controladores','La arquitectura la prevé; el POS documenta handlers inline.'),('Conteo de pruebas','Fuentes difieren; no se afirma conteo único sin ejecución.'),('Migraciones POS','Se adopta database/pos/migrations como canónica conforme a documentación.')])
    add_heading(d,'Referencias bibliográficas');
    for ref in ['Docker. (s. f.). Docker Compose. https://docs.docker.com/compose/','Koyeb. (s. f.). Documentation. https://www.koyeb.com/docs','Kubernetes. (s. f.). Service. https://kubernetes.io/docs/concepts/services-networking/service/','Railway. (s. f.). Deploy a Docker Compose app to production. https://docs.railway.com/guides/docker-compose','Render. (s. f.). Docker on Render. https://render.com/docs/docker','Proyecto Heladería Monitoreo. (2026). Código fuente y documentación interna del repositorio.']: add_para(d,ref)
    add_heading(d,'Anexos y pendientes'); add_table(d,['Elemento','Estado'],[('.dockerignore en cuatro servicios','Completado'),('Datos institucionales','[PENDIENTE]'),('URL pública','[PENDIENTE]'),('Capturas Docker/pruebas/despliegue','[PENDIENTE]'),('Video demostración','[PENDIENTE]'),('Resultados matriz de pruebas','[PENDIENTE]'),('Arquitectura AWS/IaC si se usa AWS','[PENDIENTE]')])
    d.save(OUT/'DOCUMENTO-FINAL.docx')

if __name__=='__main__': write_md(); write_docx()
